### ISSUE TITLE
Sesion de información del uso de github

### ISSUE THREAD

**Issue by ekaropolus** [ML4MX/website#1]
Saludos, 

Para establecer reglas clara de cómo utilizar github propongo que se realice una sesión en la que se explique qué funcionalidades de él podemos utilizar y cómo.

**Comment by mxochicale** [comment]
Claro que si, la 'ultima semana de Noviembre 2017 les escribo y actualizo este issue con el enlace referente a la introducci'on y el uso de github.

**Comment by ekaropolus** [comment]
Bambi y gracias

**Comment by mxochicale** [comment]
Hopefully, these posts solve the current issue: [Why GitHub and how to use it?](https://ml4mx.github.io/website/blog/2018/01/01/why-github.html) and [submission-process](https://ml4mx.github.io/website/blog/2017/12/31/submission-process.html). Please reopen the issue for further comments.
