### ISSUE TITLE
Primer simposio ML4MX

### ISSUE THREAD

**Issue by ekaropolus** [ML4MX/website#5]
Greetings, 

We need to have a landing page for the following address:
https://docs.google.com/document/d/e/2PACX-1vQdbk3JTSNGmoJ6tsUgil3gQGLwWCE3IJEJGADTxn-2LJG6v3aQM-xbbeBj3LaXg3Nqnpjy2TCujxMw/pub

Thanks in advance 
e-

**Comment by mxochicale** [comment]
[The page](https://ml4mx.github.io/website/news/2018/01/27/first-symposium-ML4MX.html) is now available at the [news section of the website](https://ml4mx.github.io/website/news/index.html)

I close the issue but anyone is welcome to re-open it for further changes or suggestions.
